enum Protein{
    SALCICHA = "SALCICHA SUINA",
    HAMBURGUER_BOVINO = "HAMBURGUER BOVINO",
    HAMBURGUER_SUINO = "HAMBURGGUER SUINO",
    HAMBURGUER_VEGETARIANO = "HAMBURGUER VEGETARIANO"
}

export default Protein;